version: '3.8'
services:
  server:
    image: gradle:7.5.1-jdk17
    working_dir: /app
    volumes:
      - ./Server:/app
    ports:
      - "8000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/happybaras
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Abrilar-542
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    command: ["./gradlew", "bootRun"]
    depends_on:
      - database
    networks:
      - happybaras-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: happybaras
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abrilar-542
    ports:
      - "5500:5432"
    networks:
      - happybaras-network

networks:
  happybaras-network:
    driver: bridge
